"""
애플리케이션에서 사용되는 상수들을 정의합니다.
"""

# UI 관련 상수
WINDOW_WIDTH = 240
WINDOW_HEIGHT = 470
WINDOW_MIN_HEIGHT = 470
WINDOW_MARGIN_X = 36
WINDOW_MARGIN_Y = 80

# 컬럼 비율
KEY_COLUMN_RATIO = 0.38
VALUE_COLUMN_RATIO = 0.62

# 입력 필드 크기
INPUT_FIELD_WIDTH = 100

# 폰트 크기
DEFAULT_FONT_SIZE = 10
LABEL_FONT_SIZE_OFFSET = 0

# 상태 창 관련
STATUS_FRAME_WIDTH = 240
STATUS_FRAME_HEIGHT = 44
STATUS_DISPLAY_TIME = 2000  # 2초
STATUS_OFFSET_Y = 24

# 패널 여백
PANEL_MARGIN = 7
ROUNDED_PANEL_RADIUS = 12
STATUS_PANEL_RADIUS = 14

# 데이터 파일
DEFAULT_DATA_FILE = "./data.json"
DEFAULT_FONT_SIZE_VALUE = 15
DEFAULT_INIT_DATA = {"font_size": DEFAULT_FONT_SIZE_VALUE, "list": []}
