"""
애플리케이션에서 사용되는 상수들을 정의합니다.
"""

# UI 관련 상수
WINDOW_WIDTH = 220
WINDOW_HEIGHT = 500
WINDOW_MIN_HEIGHT = 450
WINDOW_MARGIN_X = 50
WINDOW_MARGIN_Y = 150

# 컬럼 비율 (6:4)
KEY_COLUMN_RATIO = 0.6
VALUE_COLUMN_RATIO = 0.4

# 입력 필드 크기
INPUT_FIELD_WIDTH = 100

# 폰트 크기
DEFAULT_FONT_SIZE = 9
LABEL_FONT_SIZE_OFFSET = -2

# 상태 창 관련
STATUS_FRAME_WIDTH = 80
STATUS_FRAME_HEIGHT = 30
STATUS_DISPLAY_TIME = 2000  # 2초
STATUS_OFFSET_Y = 40

# 패널 여백
PANEL_MARGIN = 5
ROUNDED_PANEL_RADIUS = 10
STATUS_PANEL_RADIUS = 8

# 데이터 파일
DEFAULT_DATA_FILE = "./data.json"
DEFAULT_FONT_SIZE_VALUE = 15
DEFAULT_INIT_DATA = {"font_size": DEFAULT_FONT_SIZE_VALUE, "list": []}
